#!/usr/bin/env bash
# Fetch the default avatar (#41).
#
# The viewer's built-in fallback is a stack of primitives. This downloads a real
# humanoid VRM to open on instead. The model is NOT committed: it is ~15 MB, it
# is not ours, and a fresh checkout should stay small — the viewer falls back to
# the built-in bot whenever this has not been run.
#
# Model: "Sendagaya Shino", a VRoid Studio sample model.
# License: CC0 1.0 (public domain dedication). The model file's own VRM metadata
# records licenseName "CC0" with commercial, violent and sexual use all set to
# "Allow" and allowedUserName "Everyone", so redistribution and modification are
# both permitted — the two gates in docs/compression/asset-license-checklist.md.
# The license record lives beside the download, in assets/avatars/LICENSE.txt.
#
# Pinned by commit SHA rather than a branch name, and verified against a
# committed SHA-256, for the same supply-chain reason fetch-models.sh pins the
# MediaPipe assets: a moved branch must not silently change what ships.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/assets/avatars"
OUT="$OUT_DIR/default.vrm"
PINS="$ROOT/scripts/avatar-pins.sha256"

MODEL_NAME="Sendagaya Shino"
MODEL_LICENSE="CC0 1.0 Universal (public domain dedication)"
MODEL_COMMIT="e16eb187100149a315ad92c3c9968f1d5baa6c7d"
MODEL_SOURCE="https://github.com/madjin/vrm-samples/blob/$MODEL_COMMIT/vroid/beta/Sendagaya_Shino.vrm"
MODEL_URL="https://raw.githubusercontent.com/madjin/vrm-samples/$MODEL_COMMIT/vroid/beta/Sendagaya_Shino.vrm"

UPDATE_PINS=0
if [ "${1:-}" = "--update-pins" ]; then
  UPDATE_PINS=1
elif [ -n "${1:-}" ]; then
  echo "Usage: $0 [--update-pins]" >&2
  exit 2
fi

mkdir -p "$OUT_DIR"

if command -v curl >/dev/null 2>&1; then
  curl -fL --retry 3 --retry-delay 2 "$MODEL_URL" -o "$OUT"
elif command -v wget >/dev/null 2>&1; then
  wget -O "$OUT" "$MODEL_URL"
else
  echo "curl or wget is required" >&2
  exit 1
fi

if [ "$UPDATE_PINS" -eq 1 ]; then
  {
    echo "# Pinned known-good SHA-256 for the default avatar (#41)."
    echo "# Path is relative to assets/avatars/. fetch-avatar.sh verifies the"
    echo "# download against this; a mismatch fails the fetch and deletes the file."
    echo "# Regenerate after a deliberate model change with:"
    echo "#   scripts/fetch-avatar.sh --update-pins"
    echo "# then review the diff before committing."
    ( cd "$OUT_DIR" && sha256sum "default.vrm" )
  } > "$PINS"
  echo "Wrote pinned hash to $PINS. Review the diff before committing."
else
  if [ ! -f "$PINS" ]; then
    echo "Missing $PINS. Run '$0 --update-pins' once, review the hash, then commit it." >&2
    exit 1
  fi
  # A model that does not match the pin is removed rather than left on disk: the
  # viewer loads whatever is at this path, so a half-trusted file must not sit
  # there waiting to be picked up.
  if ! ( cd "$OUT_DIR" && sha256sum -c "$PINS" ); then
    rm -f "$OUT"
    echo "SHA-256 mismatch; removed $OUT." >&2
    exit 1
  fi
fi

# The license record travels with the asset, per
# docs/compression/asset-license-checklist.md step 2.
cat > "$OUT_DIR/LICENSE.txt" <<EOF
Minamo default avatar
=====================

Model:            $MODEL_NAME
File:             default.vrm
Source:           $MODEL_SOURCE
Upstream project: https://github.com/madjin/vrm-samples (VRoid Studio sample models)
License:          $MODEL_LICENSE
License text:     https://creativecommons.org/publicdomain/zero/1.0/

Permissions (from the model's own VRM meta block):
  licenseName          CC0
  allowedUserName      Everyone
  commercialUssageName Allow
  violentUssageName    Allow
  sexualUssageName     Allow

Redistribution: permitted.
Modification / compression: permitted.
Attribution: not required under CC0; recorded here anyway so the provenance of
a bundled asset stays auditable.

This file is generated by scripts/fetch-avatar.sh. Neither it nor default.vrm is
committed to the repository.
EOF

echo "Fetched $MODEL_NAME into $OUT"
echo "License record written to $OUT_DIR/LICENSE.txt ($MODEL_LICENSE)"
